{% set name = "marbles-mixins" %}
{% set pipname = "marbles.mixins" %}
{% set version = "0.9.5" %}
{% set sha256 = "8ccc01b292f44ebbaa2e38d7bd3bd14dd69eab756d310e1acd3c606bdfbc770f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pipname }}/{{ pipname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.5,<3.7
    - pip
  run:
    - python >=3.5,<3.7
    - pandas >=0.19.1,<0.24

test:
  imports:
    - marbles.mixins

about:
  home: http://github.com/twosigma/marbles
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Read better test failures.'
  description: |
    marbles is a Python unittest extension that allows test authors to write
    richer tests that expose more information on test failure to help you
    debug failing tests faster.
  doc_url: https://marbles.readthedocs.io/
  dev_url: https://github.com/twosigma/marbles

extra:
  recipe-maintainers:
    - thejunglejane
    - leifwalsh
