travis:
  secure:
    BINSTAR_TOKEN: xdqUWXt/QtH7WvFHAxxUy0JXvRRBXmu49j5W6SXPbDWfhsqu03UQCxRYHlyPDJjlmCCwui+54OqhTJGyBIcQFMFOd5stht+MaT/1Ctfzi5KvcQhKffhSlFo3VhnvyyUAfEUY8rfQ+QxZoZ+ek66eje5jYL5DXRV3Vo8GMFXLtY3bgo2TbFnggONZLz7xX6rqHZBR0KRprf6/7uiDvO2k+pTb8yI0OjzqloN6CIgeCtglY59V0Lr9vxnJrBV1St1qDs1ReNFv36pw3DLdAssllyMoTm4c5NjevYoCkQmx9L/ldY9MiXfIxoVPJO/0ARuVAWPtMtkSKvtKaRT2zMAnm2zoU6hx6zjMgSlPAMFAS0NXp1rxSej9BW3j9BEMoHBFEN4eXny+IU4xDqRVfDmigfKut6PO8rcbiWi7j7T7LK5z9xfnvMfV92Fa/ruLbzCnajslEEckapGenCCM2QBadUVNXjEQ2TvOWqM+te2BId1TL1lxixGnCgV+tkd/7QXMexkBpnO0FsPEnmoRnqNdf494g9q7UILSqBwJ7GSzCB5hfDdDWiQ1qdVy//Ws68GH5pKoLZ4fwWG5sQ9QpTTm1oxm5zJy2Th1hLzsF+5vngJV6/GhuyJCGVSa9u8D0x+yZYNdKSV0MR3+TBtoOKe9eEkiBVK+IhIR6HiavEEgyHk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
