travis:
  secure:
    BINSTAR_TOKEN: XD/EhQ5zhI2DI21aP62v6KJJ9eFdqwmiQ7XMJvdWDjGoe6bEMRi1mu3xCfUJxruyWoMIhZ97kHvCmdAI2TUK897HSba72+HF9lS+InkoAtoE89J0xKfeSZBlA9DoJ32Aqnj2r0dHRKC2BuZaHpai/wKnzFJ8rA8nOokyypU4F1sVXbbt7lWP0KOgJIyvru0nrtOTBKncGBoKbDY0RoPMlRodL43KFkKUrVTcPD+C88XwY7Q2oOZzXJCTNmXj/wXPCFcvCQV3cWAr5dEil5IQpoPnI9T5tiIb+BXxvkwqyvXkI+0j3zoc4o2UD+UYF0jE/eBE6QEQjSWAI/GcMDGJGIGvT2LlRt0tFJzbHqbDXUO2c+dC4RyPpiPa41emXG3sK9HncosgyBRIXwUMjIcYnEeKAUSxDtrnVsA6CUXsAI16u0vYdYfbZPbrQG3ELUqnmYuuAwXA+V59lkT1aXYyrcUypsXxwMbgouo6WZfnTRkz8ueHUGyjt+DC75ZeTwH0euEGMSJV9ncYBoWDSXvoYsmW0ga5BfONwtvkjQ0+Vb7DRyguXKuVE7Nh3L25MDOTIA7dGSuDZ7+7f+XDpGY0jQUS49EMLSnzytPTacgPMWgGeTH14siwP32gUJV2QWwZMugo2zSYFDdD7dhvqk8ZjPKyME8juhhnK84FubhR5mg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
