travis:
  secure:
    BINSTAR_TOKEN: mSaW2+80IK7syXu23LgF87ThFCevbUPWUxqnXq1H2BhkjTfdWUySzgYf5CTKmJs/I1QHcavjDRpCrkt0K34OPrC/n3Bm9R0j9/97FNXCec8Z6weaQaZOEMSZxRAg0ZV/4UQgnbDqKD8vpze2jNhXzLhF/b7gl6QUj30rY5Xu3zrY2aysddllFz9JKNnb2lnBq4NJqDoPq5iAqSsbDtzRIAj2JI1/7qyjm641QG5vGTtAKdnGLTvEdfkynZnQGTmumDMnXM5FDu8Hhueff+5md8wd8JaI4TsHr3eSlww1HPO/PKTNhvRE4UqxtQ77bdBcbEp21OpTbfgQ/Jqxsj1QAUXx4HX/oLp0A1M5ruZDTCUgV7HyhQvLJA1sjLwV68yov20trhuTVFvHIJwI0V6P96CdWRXZfZqVZP3Atx23emjp/k6tpmRqVyFQGPz5+E60CNamgfMjnhp/00ghaha3cTqYHkGAwRpSW5CV1ayzHz0bwRTcSvysx5wvQDgS0mTjq36n4AKo5MYQzB/LcaFtcDBsWI0/7Ml5FLONtyXxiU6iLXYocFvEOzFMmKAeWQjVVH0VZoBYKIMqZhDjvRB6Q3qf/E8AGSGUyYpoW4aT6oclYg9rpq7ISqG+2Neg3iZFiKHVqtYmRstEzw5LSjb9lANf1EUH3pyzXAssEZzfVeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
