travis:
  secure:
    BINSTAR_TOKEN: LGfmg8JJjbYsy+MaPGpLsATgBh6cP+gJj5C0RR2Qku4VC0o2hP+/tAhMx3Gyc87w9dvbr0CcT4OjWcQWIrDKcNhrc4kOsdsG5WxbVtD8xtIXVSdS0cykXNUqyibiJ1B2Q35l2QO6wUnr+3dxu9k4hidjqDBaVWhAfUBn5EN5MS/HMjWWepw5Yi0x/KmUVUllfbZAcG9+IUr/pAka72ps2LTg2+7+3HyVwzIQG9KYEJNRjLUtzvwXyl54HRD4e4D0uw3FpsXliGm94l9lekoNcFnICdT93V6+gGAwyB/bkG5GTcq+1G2PMXeJt3+SxMoMB47fOCVymHuDR7xSuJOnYlWQpJOZPXnCth2ltaYYhhspsyRmwCpDCPjuM2ngyX3tnGlrCzNr09Bor6Ps4NWdi/m/x51Xmuj8kAoq7EqOsq0XOznxa27CR/HgpoOGK15JcxH+iQmhHW20Gq9DPXdh9jp/U+zkGHqKasJofgX19bhnBdoNtcohptJtspLHWOiJSzVFMFtcviKoonBaN+4GgdZQHXL3u688YDGynlhsBp/U7Pi5D6Y8z2YGq96lAxFNeAiTz5jVndGfURTldIP5WgmF/RmpvrChiuWmKOQL/SpByI7DDgpMfhuqUM7xQM/o/2OIUY+4GcAgFCD/J7XDwn1mnz4f8hP3V+8f+XAs5VQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
