travis:
  secure:
    BINSTAR_TOKEN: gLj4mTAveUJ2CP7ayocdbKjslA/Qp4O50mfk3OFRPOPbnHExMEFoTQBydVjPPWQ+y4Dju4wtsKgs2vjAuJ6FrZCDV6dtYG20nUb+IpOEIBpVogKpXRBmV2iTmJenmGoQSZv/bJn1v+RoSAH1hSSK7ywQ7yIipkYoL1lr0STdD3UW4HBbCrOpRJnVGJF2aeZVSoz95TzJVumhmnsP1XFkyIyb84DXr6eCdHv8QKBfKYoaQkaJkHnmWVOi2Mrtmpi74O5uKJsh8hgXh5TdiucO5TFofwWiOA8n8oUj+zCPSIY85Yc0WV16pPY2/1G7FqnXao8wSr42F04xZdBjRYPwC5HigMF1CssjY8zyMSv5hjJNtLZKdSro+j2TdM7hAn3x4eSd/7pHV4UbMLDUaT0VbLfy1S/Pr+hyeSHuC8crVvgtrBH54Rdm8QjQ/k3eazRdLRpFZnoed/OcWnELXs0t67qgos83yAQvxKTKrKqlIy5F3io/zoG6YS4IUtJGLQmIgNKhyyYfObYuSC/Vm9huTm0/z9oq4ZDQz4X/A/HGBcje5f5x2U0bQQtj9t1E88fQk9SK2dVV8UfHp+cXhG/nL7Y3tXymBHz23UcE2jfq0BK6yX8IOBhV24P6GdaVMTdAs3dbjfwuXVm6KxWtgNQIae0Ow+4arnXdkdkRWO5Mtmk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
