travis:
  secure:
    BINSTAR_TOKEN: H5U8ZtPkF7ItISToqYwO73KgxQE2X73BaV6HDvxKoqBm46XdptvQ6OsAxU3Wo5yOzmA45sFea+u+liBjYOZD9x7WAM3hUc6UIWSyeEPXSPigU24Z3eeW6eszsPV/wQ+J+6+ftsSVhxgiO8CtzjCa1GeIrHsqvR//c6QkIcT47QrfgGMjttneMn7tG/48Y9YObnLt2OsdLCGdmcJHZwUiQR4ODBthzrxev1mvSExIW6SHrCf5kWpDVsL1sfQzAFqZmOtIuxWAIUKD8VikGV5Up/p/5qRLXSvr/+8vUPf7Jni5mnVBtBUFRmtZUHu77c35sG6uO89W8x5Cvyt/L1Fy3HPwPhP5tfMvTcvMxBZaKI7+e28hHXsGBxDyjdeivXNy3VRnOdJJzUKyz6gAyH95iwSnfW9G+9TAtQSCDETZ9cB5H1P0PGlax38w4f2PlosQsmTI3UdsKKi1aMN/VoSKTsPufGKQYHEaDK5jRRJpgVvSVEvNDT/9232MbnJS8UBT6C2T6tj4YeYCeGtR9XRD9JpD+4DvT9fLQXFEk7DaniEFBCZ60eAvnWg+sgB8/HXKww73F/73Tu8uEbwzOhsDuHHOBsy+o6XUQsIt3NYS+bfn+YkA/0DCFEFPMXlrqSS5EvzVz0u3J6WIHTbryqbdwuTcx1BT8sDzBNObESeBSmE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
