travis:
  secure:
    BINSTAR_TOKEN: MuaoewGdhTikL0A0kjo5k8PoJtbIgkav/TxLz/4G+kVmc92t8KLQUdwjTUVBfC4h9moMn6DZ3KYnIGlkgvBhy0gLpYSqFibVIAi/OXGp/JyCVQFXIU5GFw5Cb2xD7tgbjAYjR6eiAQfpQIodXi+9peLKCn03bZCiqJ49poht42ziJrhV4d9nEOjMsm7M2GigURGNhS42pkFMWkLnXpsdGXRwd1WddIz3ADh6jCmk1Xew2id1b3lquhauk4RHUEW7TLsolDeRoPx4hl5MVkjxXCjL5v7jmFUs28sqqtOOg4ZrP9SFhyHJie2/tzSKly5Sn+LzoIhuFGFSNu7JFtnauJ4B4c6asg+JOLr8PTiChl1mK6eZiBdIIdblgr1iOeusMEWSIFzFyQr+3DUPKFhhnejHOcoGuaW9ptU20lcst++zJq4NXM9qKBi3TiDNuiOONaEw0r4kdtWFoupaqOFmnO0vBkVNNKmlsMmYDjlerHg+NsP9p3GT+DfgMYrXEPkiIiBp9ShnXPVApfADSbIpwRcLKAnsOVKDTOQKiQYpc6cZbMg527Z0iPUBOt7NbHb5hmkiU2zjx1IpPEKNvLK9qB6wzPLvlQ8SliOho6gDWOK9XmhUHolA1uYeE7AnD7BX957gkMBIF7ZrTEIltYG/7KZiVNmZGAVIv8Nlb7/+wYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
