travis:
  secure:
    BINSTAR_TOKEN: U7W2OrxdRcpY/eQ0BYLDaei5HnMsaqLljlnnF7VxuvIXQzlZU+RfjjQwgF/4DCl34Yhr4bL4IO3nUdpYqzDzBKhiP54O2C/TNEiyl/MEq75p2b20j5DgMz8ASc9dJA7srpb0/y6ZjGBrhhH2qbdU2deSxXpXDjQjAqYVKCDWymYs0/Aej1zTw4DOYDW/oqcQ18QiSDB/ivHj1KdtTKLcYYSAA440vgQI5BUEIHmmAuJOgE0/Q7ImeXYVUboeMbDr+6VoFNC1ZOADn5il9uHhGvvzbt4+zqSr0mfdSIgSJIyJrqk5FAEgKmhz+RPj2QlwDvDxeXguQ1r25qsi2ylaT3iVnjTo2PLC9JW+BQpjKQc11Aslb497BapJ3KM+2+MQowDMxGxx8WFnn2F/Tt/tOH9Tl5y2EdGM3YQJIawiFiqYRMU8rgzLoHMOQGHzaJgcJDcJvzMgZbZZswtZbP1cUX4iiYE4/mLsBny4SSPZGL+nhLojcMopbsouwXRTOG3JrTObkg+lZeHsBiQDTKVDQmtGjV5E+QnOfEnJ/cfvChpUl721VnbFKS3ec7bcV4piH9RgpxFWFWsKlDxDxh5ZvXB9nlLXMfu5bcehp04tJS4qpyQlRxj8LB4drZgJkwTOZDbpK87i6QEe3Pkra1JSLmH12co/zQID3NWjZoPLf0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
