travis:
  secure:
    BINSTAR_TOKEN: ayEqX2oQOLOg6YW2LKVCLFJWH9y6J2bxO+0tkWcxVHVxXG52G8WHXyKPVwmut0Tm6xFaf2SSkfarRdrLC73vF6GdgTo1QrGr959zusQvUSZfLXduBL6nkcw1AzoyyJcFgq6BZmJ4sitxhWdOz6hV8/7wdO2utu7e8E0u9t2aWuoMGQWyZIBoZkclk31XL0255HCyj4APgMJGYoobkDhJe7mRsTO7caligJ7zGghUrOenFVh6HAObeTgB7BwbyTXguuMm0ppLmXL+6UJjHqIXhumjfzGZOt4VBWFYNgtquy1ylkOEko4uhUaJYO6BarxkN94CpiUIxtbEifnfgvDEfxY1KvQWILbssvRnPdJt4d46H/+XHEXtesnOO/cplBI3yLxeuYnhuHDAr1+46fQO+Tixx4wfTpb9qgn5XHd19xKV9WJG50yWns4rQpeJyrhLhIuoRdVxEe91Xk2SCfKQ1+R6J1A+GAVFrjr9xf3QddXbHV6wDFk5PhIG3qjmypnulBvY5ArFHpV5GfmHyZrbeBZ50f3GPcKvGBfoZtQGJ3Gr9DrioHXAnJtanIjRMoawJJocLj2QEE/Pvq3F8+ZDcqmdFYXRoSPu/7dLATVjJte7L6RoyB1QH/v9CruFH9ZzF7mVP4D3RqWZxtyHe0XDLKRNIrLHG6LqBTWH9iEkD/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
