travis:
  secure:
    BINSTAR_TOKEN: telHTpq1vIqbsNK1FZIIjHT3t5LA9tD2Rb/OtGPVGuxOk6N7dyyXy0domgxpQ7NSkUTFCq6yi0qcQwIVMdIJMmQtYPR+xCh8eEphY3RRzt+Md8xCllLGwunbq07ZIyZtET4/8VdzO0rQVoG7+EI4K+N9Mf2V81QrPaS4ieCpJiaNqRtx5yKwjb2Il0HmPra778KKDfLyId6nyYeo3TL6Jb0CBZ5VdEKAsmaIJ+Mrx/myjeJC6OadkMr7g7uWUqFBCNYPrFgPYx99E7HCMV8geTY7WHhq5zlZf2uiqJvf2gZK1gRe82akGt5WVinACbyjeFxkrsi8bbd2CYZL68raKhcl+O0bPLJvEn62N+vVmTrcQQe4CTP9BEL5v0y92dMEOTy7FAJLIyLVfzMJCNG46UKseyFEJN1oJUPiFowcww2NQkAM3PIbnyRmG1Sy22pncH9+evmYvhvQBZThGA1xRFuHXgWDtnfRejNyVtGwr6gvsIp/4a7IQX1ULBW8brQ9leMkNCVBsCWZsUqn99vUnbbZ812rlyo9CxcKJA1fu1++Uqr/BrjAyr1HWCvFHxE0vbIEINi69mCcsaEonVsDeH1pWuOo6yiJjmAMmK6uJ6FYK4zVz3ahJ612gRQqePModCTb/3RUGippdV2X9m98DRXxl0i9pLodCUU47jNndos=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
