travis:
  secure:
    BINSTAR_TOKEN: PTWRQuP2ZJbw7Q5dOQZlfBMcSUDnxtwIf9c8E9fFlyUV/rQeeKTOZWUWUcVpikugg1WToGoNYHb/SMQ3UREHx6vjes1JL9TxRhj63GctVae4AzXZ/74qRldx0EESDh5+kz/QabBlau1HmU9jyZ7QG7exapmnawGaX8tr7U/tUQ6ECZH2kf/sc98eSx9nFVN/+TnBXgVulvAzt7cLNCrnXVr+rDDJxRiner0KrRhuERzs5xAXwHPsM+7rMApSUB6TXgZgG5ntknRJafiaEdyQNna95tBJlMD13QZ9lEcorBBtjbEXCMJdq1sbQM6E3kkgkQYrxBKmXSRYWqUAYooTo44MCmzOp6f1CMnqcBiN9qMwJEY8s6qZjlAzpB5LuXGG38dnFxUcnvzkBcZfgFd85uk+4hdCebRsEVrJvsaMJRqHRfn0nRnmBczYmjNCUexmWgLJcGzzn+gijMWvFCulBPzJTgVUWi6KLOSixezhLRU3pE+KLjqjKfjSJCW/eQEXEvkP0ruE4G7XNbExkTF0gnrxoj6YjB5ne2tbrk11HBKnKBj+h3CVH4oEx76y4B1uj1GV5YTa33IihSZUupG8Ga4hEu14M2Hjf8s20A0fjNLBsqw28ZC7GnT9jVkkwssrigNnystTP2acYpsIz0r5HsIWRYGOouRgEjgiUAObqyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
