travis:
  secure:
    BINSTAR_TOKEN: ecTwW/nMz+B5V3OHWHOHrS+q4946FsDp2Vsynq3indwUx614857IgqhF8HoMBxetyu0rLlNAtKdqpiUN162Pq1w0nNPLOW/D43GKx2w61iI2y/jTPN04n7zZENc2c195wzV59x7rB9G44fhMU9pOTLY1uqOsD6vkB63jl4Ox2He89+KMZ2zy4JquhWA4kQEpP8lWZxwgJWFAPwOcvQjzoillN4+7xexyCPqhPLvntMJEqWt5aRMn/mXA3zRZs+L71QaCdu8v09zH4fddnZzFxDjSRk/ev0VQOYowpxU+sd8EoDzUP6q2YMorx92Z/n7/aSubJA6UlIfw+4jE5RR+eMV+EEp8HFbHeGcfc1asGL7CWUkrrZAX8kfKdE2WuWnxQPjuvZnTGPVNn1ISLjN3g5GGuUPvLRjFwAY1kq06EpSJGTarloLt0mcvVgnXt5/ZtCPa5/LLhGM2Vdf7MuI5hjZ5X9b+q5UcEDLEc26ymKJs14qJ4WENJEMOCKAEAlo5zR/v8EZP/YezW8vHRjXrl1kreGrPV8IZCDK0aqbEpR6QhYnNO+xRrw8FYiiY0znC9y6APd4Wfs6hxIaRUi4qiUS8tSxm+foeHkaAfG4loefYeQrSiW4xGr7458/dH8Y6hzZcWkljDn4TKtRDN1IWyUoSjwQqSOMzkuoa25VzWzY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
