travis:
  secure:
    BINSTAR_TOKEN: R3utHQ86voxJb/DuoO8nuOxmmYkHXkyEgOes1RyLEwnIQNTIg8XjkoP3ev9ATW5KuXpk/M4ky55u7AFXEC737sF6zpxSVApQ63zX0ToqFgCyHW6oqcvr6NxNVhKlF8Sw0JcDsFEHTdVP4H8hQCTDxf/MM8hkET07d5ame9LK3oKhaNGChsi/GqB3SBQVo4JM/vOmdzhb9rVaqKIYaiHfolKD7pNqUI5ujcuvDsYQTyUTZM8NozSqZXgXcRilcAuWQa/9eVGql9opCtG2QSWaFKud+CrGBbZG+VfQIjCJA0IVbd5JMELvDyP0DriC69gqNEiIed4iNc/NVJ/37MwEpaXMj8U3rDxHOmjzP/A/SViH+Mun1gBCcynEcMa3bQKYOPJJbtWyNv9FYurMwcB2Dzogef3Kg5FICgCOBtxvBF+LDYBWb3fsK7pRNA8YAoo1FwzJ9/MWPS7tCISTOmdSGbgcIsR8uQM26DiVzEy8HEq3qpJz7HHXVJFEGCK/+w2QCEAnLKJg4fl3mPvsChx69QihToRUmC94dodqbPTZHbsoGHz+RchoAAFeBsawru9vC2RJeXLUFHozAciPy1VxD+vc5oDLdqWim9rtN4V1pA27iuELhpLDzTkKo/8LNm3YnutvGhdTtcZgGDcah/AErT4suxBIzPlwKyVQllAUfPg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
