travis:
  secure:
    BINSTAR_TOKEN: GfZ1xyqmZ24qmJDcJdlbCTpStZ9baGKtUd49q/KRWHtLEASNO1+i1pNZDqjmHLTL10kRfxkwyzjyTFr0kGJmwwmXt/Yj+8ag60l8FInQzrCl85AXIMwSspXkYpieTftYi38jyJdKHkiccTRrVOR8OeIdd/DS48fJt2LUeZN+mtfaQ8u/Nuaqj7+kZTPTL84f5L8AoyHtUGs2Tz80yMZBbC7Ga31VG/7DnJUKqZflba6wqRVvZZjBo592Ma2rJ39KarSrkAU4Z/T5TDjsWNaTD8AxLKmuvy1BhZUqkdtmXd9pL57jAOPz+cVztr3ym5IZXZKoa7+K2PYHuLLN2f+O0ivHiZlVOC9KFF4e4zUyqPQhiVR7o7KycbX0WSn1W6F3lr8C2CmPxmHYtz+/w9jOMlRYjVbjO0A+CSKFZD+b+gSsFbbAUX1ony8R3BeHEU1Kk/g9w7zEMz3395qTGHq+9hBXbW37vc1017idIExc+zuwkS795by9z3h4ROQkrDTeGp9o1F/TnLypDKZiBwlUgO3UYTR7vqGYe0HSh/PD3R+O8ZxqFHl8BcpcC+C/T8NLnmAjIXg8jpjXK/B9vL5AUDfmY+ULpnVyPIl1Ws7lPkQCiTbMxHcpaDX5B72P2AOf/1rSxL1roEyIubGZdBj2WWLJ4QORZfNQ4kJgbn3+Edw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
