travis:
  secure:
    BINSTAR_TOKEN: h0SVKOk9AfNncoa+NYYbdSblYLeYekhTo+YnuATsHjyRIC0yPscYB3x95yWzNEkyZgAuhZMdzuAze7ym7Krjti5jEv5soUV2h/C+CWqNuLjxCVPJXs43jjVtRC8+uJgI7/RJfs7fhOyiY7n6tNd0UvfQq3VbwVVEOG0F3t0oYO4RblCS/qjTlL3h0FwJiqASal6LHFQj/RENvGebUguLNh1Rs21iaXYy5BAJwCDuHDRf0+l7mtNVdUB0RfhM3+bdsLZY2rt/8V9fIVlm2YqLtIGMZgPYHlgLHc8sJ5J+ByyMfYKj40Kqk4DnMvqjPZL2UqowHw3u++s1hhrJij1UQqsKTbLXmP2jsaoVlT+rhGAm06OgCcxtP/Mwqb6FE3pokTcfzQVJPwIG/d/K1Dl1cWsCerP0Hk+kp1h/43+CrVIVXmR6db4J5PQ0D+ORbIXAmvDalpfBa96eZv0ts14ck99E7aHBOcDvO88BWIcaA29eIgNATcN/3ljFEfJhRi3cP+ciGu9g5SMll9sI7b3gonpozRegncUDPGAmaGCrzMwfiXyg0WNFutFXc3AttAC2VuUcvy74kdl9MsNg3e33hqjTFSW4BMZezDgoIsgGR0I/zeW51snKoKQ94RgoLad+V1QbjxVG7D44MmOIPNQcFFvTp3IoscDdja6P6tpMq6E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
