travis:
  secure:
    BINSTAR_TOKEN: Lgp3nWr5tciH0aIYWt9jCqCbDXwx0jfjCFQfcRt7lNpKavayhkG9eJgiSA6izFWJCawYQFHOAb5DRYT4Mfa+Nbgqk/yJIt5fQI3klAZxhiQOgyrJaS7kiaLZpr3FCfVhWnhuqnY7VJMYcLVHqkjUz4nMrVCwW8RCLNcB2tsPsWjdhlyrcok6xVgsv/WsRyLHmlyqEZ/ZcrChhI1OtASWepSiKJWAvR+zgKyI15c1BOKZ6GgCQUPZZYTi3BkymjLWenXvlsyvol7sjP1+hRi5qLyn+Z6cjC1xV031I7ps9ybW7Ir3Q1oiguC8mkH5JoNrsb0rJwuJ5T/vr9YRC1vC6BQ2UQAHG/zg80ABHiGDX+9K7/HPWFS9Qvcz5x5VEeIwQohiv++TgvF5FyNtriXBCnxnUP7un6t2GmNX7tGhvaQsHQsEIRwgzgD/ex5b0yjgJXfWjnU+j/ZeRbBIJLlCXv0IZn9qQkGEfHdpBNp4TI8ArYUXQ0xDjLcVG7ZY+0G6HMYIXzgjwBJb/4uafzrhx26WgI1MLzyg+cWxeZMKLvlO90SAcgI2eD2MCi948oucMEtBnIXsWYp4uPlf81aGaTkVHM2WgR7V125qqu/pyJvYwkhSZonxhyLqYrAIpLpHuwLrmrZ3MzHcsHJHdWYzQfWrIeDkzPSrmzvxxzmFmqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
