travis:
  secure:
    BINSTAR_TOKEN: Mfgvw6/BVmO6QNl36zut5T+BKoZa3vkzVbT7l8dgm6ZnfMkYpkrTgQ2YXN8YL/4pI9UYThYYtZN/w+jaafgIkit28y0wIRwxW+I2Jae799WDcSwpCyUdKqDzgkB0wBigqQBrRzTmYAnvYvu87bNtM6ETnhiZGI1EobpqaH38aFlxvixtSlCrDidL+WwZqQ3jT+P08k6oXKOOHL1FuGBFu/zQ/sg5bULhnBAdw5XLvd4Yf8/3CC4uDBGnnQ/6MDEyQh7rpGGLOYFXIlGgQTg/yKFs8tMwD0Gm0htDTfUvWFKwAlhCLj8pmuEJmZtNCh9a0RT1TQhpAmES3w8h8uWyFR5Wmw7IifNgsHhCdJ74RhzhTX/3uMrf6w6oZ0g9NO1KBa68+9WPWAw18yLKx8nMy2g4rvCIezD1xd1ff6n8sI2yGveSlXqq9g7DcfE8YNzr1OulOaineUtf0fDjjR6HErHdGVJ/aVxwcU37ZFJcZDuHxqTZXo5bgbBRMaXGs8c+PTFUWDSwMCucuQhH3vYXA5Qr7sbUYCAsapNK6ztJlaQHyNoM8l+cWxKAipLvbqiydBTUElTTYj+dLvliOElyBjs/giWXLtYlmO8UOmmUT2EpG4oKNT9DLxjRft5OVJFrxNDD5W5Dl6NDHudEHhm4wVtOAWdZBGHvESZyvUgMycI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
