travis:
  secure:
    BINSTAR_TOKEN: g3jr5eF7AWQ32T+bNnLNhr0tSp/Pd22FiLZuD6yl7b58oeAQXTy7r9XtkTp39MW/bp8B7ewAb1qjnTu19KgYiVTmsHuNAScf93erKzFm3lEw3SdQRfJAfNpENTOrMe17FUtTXwrY2b3EdXVz65mUrJHalOVpJg4mxKexZQDgIM3+jwLZMrSthuMaVm9eTYMtYnkrpT6Ue4yKcFSPEY7aN/utZdWEc3qyBh/+vK8uBr5V0BHemZu/+VER61SFee3MnhvMeAhIjos1qaT8us5chA10UQzkHBzd6g1vFFJUMBCFRPqP9nLeeujBpsr6Op6E8sSKECgcunAgWD1N00cRLKIGVmEAxXxcYFns/e7vJjBbUZ5RI69bgNn/hRQSRTl+/Yg74CYVGRLkgUb9064Dlufig3MLtDqw+p5gCCadNwGARTy1euQK3ahp2EiSUy3niczLNuReYk+jdg6qabAPwAwI3xVV3v/9me+zIGkdywjfmR3rNsvidckRgQf4zEKiI9CMyiV1tVfC1qwU+sigu5xpmRhJjUB4zuslDe06AYEo+PMNznWq5oA0cvHJUbv87Qk28BarCEI2tNqrFyk6Sbj/1H3QJChxe4+pXqHTZD6EO82xIpi8f86yplx2S8z+CbiAkBkJn5xnsCapCZN8GoJExbykFaosBQBUta9tBSM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
