travis:
  secure:
    BINSTAR_TOKEN: XRYOKctsDAvZ8LDD47CklEbsdraVnFeUn8mwm6DW22NyqMZy0ExO1IIVjkstPwm9hUjDl3C934B1P0SbPua0yflpwRcPK1uUaHMkS1TurMTByeeO624GDvPw0tRwck1YpyOmhr3m2EGqE7klLMlNw0ZF/XUvcfeT6mkXWAthHN7VgKkGrlVjMdJ8h7IKufuZQT54woeBn4vFEXxCk/0hB3ClVTumGKn1dAJ+tMok+MpM+d+tRjBWRbNPaKu1FN7dcs7xjiaa1Oa+EMe6UNIMnic+zCO04ruDPcOKB/ONNPdKHnuq98AvYdLJRL0Lnee0XqgJd2Q9A4hdM7Phb7oBEpgEyc2IOH/OJO+gxTfqectGIs3qIg+hihNZJO+yW3q+Yty4c1fewKaCXcLlS0HYWBpfPO9oQZX0XSy3fFZyHW9Fy7nSXn8RLvWdAKqpsGAhoTAtCl7dhVBPmVocTVTfEsiL++NLo4nQQpyp+p24Olw3d1OeUANUeoQSGDVz/MOn0PCH+eXe0/6oPiWl2WpCKIXmLdWyYzCVKnEMK6lcMrL/7dDARLct4apMW4lDjKJvcSEr4+mGcGVXqhVuesa0Y3M2NyVnl2WWWP/Y+lURLA6c7ORC5t1+RgEaYzw7U1ddXrt74ywBCYemgr3/WdUvxicOzm1cEnPAFLWZcRO2ygs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
