travis:
  secure:
    BINSTAR_TOKEN: X3wzW13oK+dbcA9+NfB8y/6qJYyPNuTYNMJL0mGqPqr33rB114ky/Mbg4jgEGRqHnCC8ht9am/+bEOT9dJDaggNBQAWg/KynfDVvUNzpKzL3sJ35rOCrRhhByitdF/XBkOdqKdofvPu0U3pYhTxY3zU7v/cPnsh53IBVLz9Rlze3w6qINenR2GYMC77R61CaH/XwQYoAQ5IX3IH6YEtlvJiRYa+FDpUqt91Dk9f2LN7U3RQZLq94bITqqm8AoNUUHCciyEpt944FITNl73j8Z3UaW5g2MCKkINZN8BpQMhEbw5CUMoyYE1c/twmh55K1+xz0g2kBYTrUZ0OZgCHqI3IWpnle44qqZsXDjK4R++AOrf6W53EYKPKv92hYF0j+mWBsJqsW1sH7TUnIbWj4QS0qIqxwrHI4IGWkbF6yemTrKDJ/yccT3x40G4vQpSa2R5e12bYS5cEB9bUYsQbYIA3oTcd+Q868ooe/VNKvpflUh2x5b1HxB3jxppfRn4YZw2kmpnVmhoQ0VZJfwFT2/KVaXWpKYWB3NfW9Vr0BwqTaAJocvbJEGzg9IP9TJaMtwvhsc82bOV/KSi6TAPN5LZjmSYf+E2YUEOHHtENksT1RrQ5Iluf0tDyRHLvCOot5jTNZSnwnbMkQlUlpkBkyaE7/Ry+/VS+pk2MSZBHCjh0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
