travis:
  secure:
    BINSTAR_TOKEN: TBLWsZD3HawbuG3r5KAHyHyKgLnOZ4Hw0/2Lk7JVFnorldm0qO1Oq8l/HxzDec5wJLZiiLXHay9cIR9hZIvIAZjJQU+Q2NdpmCSLcsQTyMNAE0Xs7oQ8zDOX5Wf8IPsjIK/le5sfNAnaC0zAcHH0eO8asXWSKezygGGKUdJ8yp+o+B1IyF1iiGbedFjKGzXufJs8c6jGNG6ouBgJDqNxGUBnasvrZxZ2qCES6olGCDg0Sezw+XXecc0TQi/V+Vi5pkhTN9PaR7NtIC+Ck6s8MbZqjgYERC3aSvFAnJd779VdJn85YtY0o90jMGZk+NSmLntiIkh9ju+73SchkBCBRC7Z+LagiDQGR5CDuTtdVMHL5pPr1tZV9gFeY7XaMrj93BfiQh4sRmxdidQVnSrE+5bqEYLj/qwULKakEV6Dm1nS3Wob+0CSbrPq9oMMPwOPnXKlIEW3NRt+csiEtElCsCqkM4DHu2SBVwbs9bzYrkQuBB5p5KZJOB9csW5l5Ool62+XwKzvfuDQZ6mM0dE0vzy9uB12glAt+vDgTmoDnlBzmVWcsVzJ39AEl4txCrX/k5fRZ4eGWz52PVt/VoIsN4nO9GODcx1igtea3vmGIgkxxH1LnWbyFDqDWlGndD5R27HMadVAD+npnECs4BMJnpTIm8UhoGs7y9bhL4UrUFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
