travis:
  secure:
    BINSTAR_TOKEN: M92OKfYp0rTkq4qagOjsLT7KyJZq4l2F9G2rSsQMASBpBDah7m/bIwe+hOsKr0b1eZanyL58RkOJj4fWwvkUCyxNZgCG14Qr/mvx6zkeMuasjPZYdOakiOIf3O+ULqqZtbA5Nsxjhb83Yy4niMJjvU1E6lov0RI2f8sw3bzASHnmdJpIQ/XgJFbf33sZkr29+Fpi3kDBzFs7sTqcHqB+PoX3ThvixRZdPj3bCe8NUohGI3cR8noSrsDq5QJ3kJ11/YraaUbIPQjp68bMLH2xwsnpYbH3xA/q5noN0K1pc7BvuGvrdNzqa0jTYnyW6xhaOkKctw+3uqspYFqRVawsgp7LuQbQCqSu3arzbYx9rj/VzyZwI/eMHn+nbls4JK2Yjjn7NLtfyZX4whOCZtGyAPll1YEK2i7QHPGAy+LrGlGQkKSlKL5yP/quDhovSSPkA+ajWcdh5qkBOGuTurI6a0/B1GkSVkiM4vdzT1XsDJOw6lSWjKpcsq8ewMxG8f2GGDMxxL9S1X2/68xotiid1e9sbW6/tkMqXdy60JDczZz4dLrEYyDMYMjU4NIytnEwdFobNPvQP/XlPAPjAIZlICm4nye4069PDrLmnOs6LO3aDguEfBPg+oKUnLLZpEz9ak5hv86pnrRFqJFJQpydm4JqSVrF/Ai584nPx7BngW4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
