travis:
  secure:
    BINSTAR_TOKEN: MsrtpSYhPSMZ9zb4DHFAyLm2wC7WtkzlE+KYUpYaVpigrI/m8IYlAblgI4xxAHuK9lsmG/rt0/2Nt+bMkWCbrmPRSB2/Xl9fesslTVrK8UZ29Bk8+ESRSzh6MmPQy2G/7otzu2QrKzodYzomNz+b8HnYz/9vIR+7dMfrNXGoTSRZN/fHPFSZH+mJN7lu+LdUSoCnbdj+1LsRH5iGdHy3/cKj6z0CSFFhJQB0jtXU360DoH6UlIvp5qXFEGoqn36+6Uo8TLAg3ZsdLomeNn3sUdy1QpFlmQH8sEJMmh5TvR3PId6C4XjrAzux7PCkIvOxQZd75WfVBObgLiHCpKHv97utMIXWM+YMQgc18BI5l/fqUHPaGHJ6/SYJHWRednD9yit0E7AaJqe1fVYiENZjSiSVZ2LJ9yPXXPBJXBfTnelq5TXAZ34k2ki7SjKw/lnZDX+Es7phEy/iRfVlWOgomvvpSQfAadArYAiYeZxFcTFTlPErDYilgzSTDegv+2jSTfXA29YArPULxrzJRTpABS8n8WY9Sk8//npq63pF1mXgGXWP1q8qMIuZ99IqWTfY8bAvPsnAd/B7UiibXEiDfkgBfc6UA+mPTQ0JfsAFJu5OioEJz7DAIEODELeEg4vkYWUJEJHIsvhrm0NOLBW3cnqh5qnr/2zHkU8eRX5ZHa8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
